export const REGISTER_COMPANY_REQUEST = "REGISTER_COMPANY_REQUEST"
export const REGISTER_COMPANY_SUCCESS = "REGISTER_COMPANY_SUCCESS"
export const REGISTER_COMPANY_FAILED = "REGISTER_COMPANY_FAILED"
export const LIST_COMPANY_REQUEST = "LIST_COMPANY_REQUEST"
export const LIST_COMPANY_SUCCESS = "LIST_COMPANY_SUCCESS"
export const DELETE_COMPANY_REQUEST = "DELETE_COMPANY_REQUEST"
export const DELETE_COMPANY_SUCCESS = "DELETE_COMPANY_SUCCESS"
export const CLOSE_MODAL = "CLOSE_MODAL"

