export const REGISTER_COMPANY_REQUEST = "REGISTER_COMPANY_REQUEST"
export const REGISTER_COMPANY_SUCCESS = "REGISTER_COMPANY_SUCCESS"
export const LIST_COMPANY_REQUEST = "LIST_COMPANY_REQUEST"
export const LIST_COMPANY_SUCCESS = "LIST_COMPANY_SUCCESS"

